### PR TITLE
Alternate solution to 1-16 which obeys spec exactly by only modify main()

### PR DESCRIPTION
**Pull request by ibnIrshad**
A completely rewritten solution which follows the spec given in the KNR book exactly: make the program work for arbitrarily long lines by modifying main() only. I've only changed the name of the macro MAXLINE to BUFFSIZE for clarity - otherwise the code is typed up exactly as found in the book. It demonstrates the use of a buffer without modifying any of the helper code.

### CODE REVIEW

**Comment by ibnIrshad** [comment]
Hey Daniel I'm a beginner to C, and I would greatly appreciate if you took the time to review my solution (and the commentary/assumptions I made). 

P.S. This is my very first pull request on Github!

**Comment by sporkbox** [comment]
Hi Isa! Thanks for offering your perspective on the exercise. I hadn't considered altering *only* `main()`; that's an interesting way to solve the exercise and it was probably what K&R were aiming for, by forcing the reader to use the building blocks together to get the desired result without modifying the functions. It's been a while since I wrote this, so I probably got wrapped up in details instead of looking at the big picture. :P 

I do have a few "nitpicks", so to speak. They're pretty minor, like code style, typos, and commentary. One that stands out to me is the lack of wrapping on your commit message. I prefer to wrap at 72 characters in commit messages, and 80 characters in code comments. If you don't know how to fix it, you'll need to use `git commit --amend`. Just be sure you have nothing staged, or it'll get added to the latest commit! If you'd prefer, I can do this with my local copy before merging.

Speaking of that, would you prefer I merge your PR and add a commit to fix things, or add comments to this PR directly to outline each item? I will need to add a commit regardless, because I started this repo with a README that mentions they're *my* solutions, and that's now wrong :stuck_out_tongue:. To correct that, I'll need to add a CONTRIBUTORS file and revise the README.

Just to clarify, I do like the solution. It compiles and it works, so that's important! :smile: Thanks again for contributing!

**Comment by ibnIrshad** [comment]
I think I've fixed the glaring deviations in style (not "nitpicks" at all!). If there's anything else, please go ahead and add a commit. I prefer if you merge the PR first, and then add a commit to fix things in the README and so on. GPL v3 sounds good!

Thanks again for guiding me through my very first PR.

**Comment by sporkbox** [comment]
Thanks for cleaning things up a bit! In the next commit I'll be adding the modified README, and I looked into code formatting tools. The CONTRIBUTING.mdown file (upcoming) will explain the guidelines in detail, but I'm also including a configuration for `astyle`, which can be used to auto-format for anyone working on the repository.

Thanks again for contributing!

**Pull request merged**
